name: Ml_predict
channels:
 - conda-forge
 - defaults
dependencies:
 - python== 3.9
 - pandas
 - pytest
 - isort
 - pre-commit
 - flake8
 - seaborn
 - ipykernel
 - nb_conda_kernels
 - pandas-profiling
 - pip
 - scikit-learn
 - imbalanced-learn
 - hyperopt